import json
import logging
import requests
from jira import JIRA

# Setup Logging for IR Forensics
logging.basicConfig(
    filename="incident_response.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)


def trigger_slack_alert(webhook_url: str, message: str):
    """Sends an automated notification to DevSecOps Slack channel."""
    payload = {"text": f"🚨 *INCIDENT ALERT*: {message}"}
    requests.post(
        webhook_url,
        data=json.dumps(payload),
        headers={"Content-Type": "application/json"},
    )


def auto_create_jira_incident(summary: str, description: str):
    """Creates a high-priority incident ticket in Jira automatically."""
    jira_options = {"server": "https://your-company.atlassian.net"}
    jira = JIRA(
        options=jira_options,
        basic_auth=("ops-bot@company.com", "YOUR_JIRA_API_KEY"),
    )

    issue_dict = {
        "project": {"key": "OPS"},
        "summary": summary,
        "description": description,
        "issuetype": {"name": "Bug"},
        "priority": {"name": "Highest"},
    }
    return jira.create_issue(fields=issue_dict)


def process_incident(service_name: str, status_code: int):
    """Incident Response Handler Workflow."""
    if status_code >= 500:
        log_msg = f"Critical Failure in {service_name}! HTTP Status: {status_code}"
        logging.critical(log_msg)

        # Step 1: Containment / Notification
        slack_url = "https://hooks.slack.com/services/T000/B000/XXXX"
        trigger_slack_alert(slack_url, log_msg)

        # Step 2: Auto-Create Jira Ticket for On-Call Engineer
        jira_issue = auto_create_jira_incident(
            summary=f"P1 Incident: {service_name} Returning {status_code}",
            description=f"Auto-generated by Python IR Bot. Logs saved in incident_response.log",
        )
        print(f"Incident Logged Successfully: {jira_issue.key}")


# Simulating an HTTP 500 Service Failure Response
process_incident(service_name="Payment-Gateway", status_code=500)